name = "Contextuality"
uuid = "0f4f77b4-1350-4452-bb84-60ebbe094f29"
authors = ["Likan Zhan <zhanlikan@hotmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
